### ISSUE TITLE
Create basic Grid

### ISSUE THREAD

**Issue by caal-15** [in-silico/judge-frontend#14]
We can create the basic Grid like [here](http://www.w3schools.com/css/css_rwd_grid.asp), but as you can see this method implements two classes "row" and "col-" this means each component should be wrapped around a div from "col-" class and a collection of components representing a whole row would be wrapped around a div from "row" class, this also means that in order to not use any of the css classes inside the react.js code (which is what somewhat hampers modularity) we should output a file for each of the stacked components we create and not just output a "bundle.js" with everything, if you see a problem with this, or have different proposal, please comment.

**Comment by caal-15** [comment]
I have tested react and CSS using the grid provided by W3Schools and made a little example page with it you can find it [here](https://github.com/caal-15/react-tutorial/tree/react-css/), the bulk of the work is in public/css/base.css and public/index.html, the react component itself was developed in public/scripts/comments.js

**Comment by aerendon** [comment]
Added [here](https://github.com/in-silico/judge-frontend/blob/master/public/css/style.css) by @caal-15
