### ISSUE TITLE
New logo (In-silico)

### ISSUE THREAD

**Issue by aerendon** [in-silico/judge-frontend#5]
The task is to create a new logo, based on brainstorm.

<table align="center">
  <tr align="center" width=50%>
    <th align="center"><img src="https://cloud.githubusercontent.com/assets/14989202/11605843/479f76c0-9ad8-11e5-8485-94834a5c894f.png" ></th>
    <th align="center"><img src="https://cloud.githubusercontent.com/assets/14989202/11605884/81603eb6-9ad9-11e5-85b0-8502bf3d7a1e.png" ></th>
  </tr>
  <tr align="center" width=50%>
    <td align="center"><b>First Logo</b></td>
    <td align="center"><b>Upgraded First Logo</b></td>
  </tr>
</table>

## New Design:

<p align="center"><img src ="https://cloud.githubusercontent.com/assets/14989202/11605968/21ac0906-9add-11e5-8be8-fa37a02e445a.png" width=60% > </p>

*The main idea of this design is based on a circuit (For the meaning of the word In-silico)*

So, what do you think about this new design?...Now, brainstorming :sunglasses: 
_____________________
## Last Updates: Version List

<table align="center">
  <tr align="center" width=50%>
    <th align="center"><img src="https://cloud.githubusercontent.com/assets/14989202/11617626/95ee1088-9c5f-11e5-97d7-019179b6873f.png" width=100%></th>
    <th align="center"><img src="https://cloud.githubusercontent.com/assets/14989202/11617627/95ee708c-9c5f-11e5-995e-1bb7eaf308d7.png" width=100%></th>
  </tr>
<tr align="center" width=50%>
    <td align="center"><b>v1</b></td>
    <td align="center"><b>v2</b></td>
  </tr>
  <tr align="center" width=50%>
    <th align="center"><img src="https://cloud.githubusercontent.com/assets/14989202/11618763/ebb12ffc-9c6c-11e5-97e8-57c871804ad0.png" width=100%></th>
    <th align="center"><img src="https://cloud.githubusercontent.com/assets/14989202/11618940/819816fa-9c6f-11e5-928e-d6faa6c4f9c2.png" width=100%></th>
  </tr>
<tr align="center" width=50%>
    <td align="center"><b>v3</b></td>
    <td align="center"><b>v4</b></td>
  </tr>
</table>
____________________________________
<div align = "center">
<img src = "https://cloud.githubusercontent.com/assets/14989202/11767935/c43e958a-a18b-11e5-9712-b65e92eb6032.jpg" width = 45%>v5 <img src = "https://cloud.githubusercontent.com/assets/14989202/11768037/94347c26-a18e-11e5-84ad-a8554c9fe75d.png" width = 45%> v6
</div>

**Comment by heticor915** [comment]
It seems pretty cool, I like circuits, the only thing is that  I'd apply a gradient to the letter or stumping to highlight the letters.

Nice work.

**Comment by leiverandres** [comment]
Why not somethig more code than circuits

**Comment by pin3da** [comment]
I like the new idea, @aerendon could you add the image with 'filled' font  ? 

What do you think about Toby (the dog) ? I'd like to keep it in the logo.

**Comment by leiverandres** [comment]
And what about square instead of a circular logo?

**Comment by heticor915** [comment]
I agree with @leiverandres  about the shape, and I was thinking about the dog, Why a dog?, what is the meaning here ?

**Comment by pin3da** [comment]
I also agree with @leiverandres, we can explore other shapes, for example the hexagons http://hexb.in/

Toby is the Santiago's pet, there are a lot of histories in the group about Toby. In fact, Toby is the protagonist in the most of the problems for the contests.

**Comment by leiverandres** [comment]
hexagon +1

**Comment by leiverandres** [comment]
This is the tool I told @aerendon  https://color.adobe.com/es/create/color-wheel/?base=2&rule=Compound&selected=3&name=Mi%20tema%20de%20Color&mode=rgb&rgbvalues=0.46416809881274407,0.31550469762168176,0.8,0.4579771287872848,0.3951075711104823,0.6,0.4943808720271021,0.6107948158807446,1,1,0.9211870262242774,0.7872535759379167,0.8,0.5598613067066927,0.31550469762168176&swatchOrder=0,1,2,3,4

**Comment by aerendon** [comment]
### Update
According to comments...

**v1**<img src="https://cloud.githubusercontent.com/assets/14989202/11617626/95ee1088-9c5f-11e5-97d7-019179b6873f.png" width=45%> **v2**<img src = "https://cloud.githubusercontent.com/assets/14989202/11617627/95ee708c-9c5f-11e5-995e-1bb7eaf308d7.png" width=45%>
--------
Which version do you prefer?
*NOTE: The palette of colors will be replaced*

**Comment by leiverandres** [comment]
V2 :+1:

**Comment by pin3da** [comment]
v1 :+1:

**Comment by heticor915** [comment]
v1 :smiley: , Where are you going to put the dog ?

**Comment by sebasvega95** [comment]
v1 FTW!!

**Comment by leiverandres** [comment]
:-1: v1 ajajajaa no, no space for tobby :cry:

**Comment by sebas095** [comment]
V2

**Comment by aerendon** [comment]
## Update: v3
<div align = "center">
<img src = "https://cloud.githubusercontent.com/assets/14989202/11618763/ebb12ffc-9c6c-11e5-97e8-57c871804ad0.png"width = 70%>
</div>

**Comment by heticor915** [comment]
I will change my vote :+1: v3

**Comment by leiverandres** [comment]
parce que tal este asomándose
Format: ![Alt Text](http://frenchiemania.com/wp-content/uploads/2014/12/vinilo-coche-bulldog-frances-negro-3.jpg)

**Comment by sebas095** [comment]
The idea @leiverandres is great in the v3

**Comment by aerendon** [comment]
## Update: v4
So...
<div align = "center">
<img src = "https://cloud.githubusercontent.com/assets/14989202/11618940/819816fa-9c6f-11e5-928e-d6faa6c4f9c2.png" width = 60%>
</div>

**Comment by sebasvega95** [comment]
I think it would look better if Toby was like peeking from behind the logo. Just an idea :P

**Comment by caal-15** [comment]
What if we change the color from yellow, to silver, kinda more circuit like, anyway, great job, I kinda prefer v3 over v4

**Comment by aerendon** [comment]
## Update
According to comments in the meeting with the Frontend team...

<div align = "center">
<img src = "https://cloud.githubusercontent.com/assets/14989202/11767935/c43e958a-a18b-11e5-9712-b65e92eb6032.jpg" width = 65%>
</div>

**Comment by heticor915** [comment]
That's so cool, Can I change my vote xD. I'll  vote for the last update please keep doing the good things that you are doing now with the logo.

**Comment by pin3da** [comment]
I really like the last version (v6) :+1: 

 I'd like to make one small vote to be sure that this is the final version.

**Comment by alsuga** [comment]
v6 is cool but I miss Toby (the version of Toby in v4).

**Comment by caal-15** [comment]
It looks cool, I was wondering how it would look with a light blueish font color, can we try that out?

**Comment by pin3da** [comment]
After voting we decide to use v6. Other versions of the logo will be available [here](https://github.com/in-silico/logo)
