### ISSUE TITLE
Define technologies to be used

### ISSUE THREAD

**Issue by caal-15** [in-silico/judge-frontend#6]
We must decide which technologies are going to be used to build the frontend @pin3da suggests [react.js](http://facebook.github.io/react/) + [browserify](http://browserify.org), I have been looking at them and both seem pretty appropriate for the development, though I'm just a begginer on both

**Comment by pin3da** [comment]
@aerendon is working with materialize, a css template which is pretty useful. I think we could use it instead of bootstrap or plain css.

**Comment by aerendon** [comment]
Link: http://materializecss.com/

**Comment by caal-15** [comment]
Decided to use raw CSS fro development

**Comment by leiverandres** [comment]
# StyleGuides
1. [flat](http://designmoTdo.github.io/Flat-UI/#)
2. [mailChimp](http://ux.mailchimp.com/patterns/)
